# 데이터 전처리

### 1. 레이블 인코딩

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [3]:
# 레이블 인코더 객체 생성
encoder = LabelEncoder()

In [4]:
# 데이터를 주어서 간보기, 일종의 학습
encoder.fit(items)

LabelEncoder()

In [5]:
# 인코딩 변환값 변환
lables = encoder.transform(items)
lables

array([0, 1, 4, 5, 3, 3, 2, 2])

In [6]:
# 실전에서는
items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
lables = encoder.fit_transform(items)
lables

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [8]:
# 고수들은
lables = LabelEncoder().fit_transform(items)
lables

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

### 2. One-hot encoding

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
lables = LabelEncoder().fit_transform(items)

In [15]:
type(lables)

numpy.ndarray

In [17]:
# 객체 생성, 학습 후 변환
oh_encoder = OneHotEncoder()
lables = lables.reshape(-1, 1)
oh_encoder.fit(lables)
one_hot = oh_encoder.transform(lables)
one_hot

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [19]:
print(one_hot.toarray())

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [20]:
# 실전에서는
lables = LabelEncoder().fit_transform(items)
oh_encoder = OneHotEncoder()
one_hot = oh_encoder.fit_transform(lables.reshape(-1,1))
one_hot.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])