# 평가

### MNIST 손글씨 "Is it seven?"

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.base import BaseEstimator
class MyFakeClassfier(BaseEstimator):   # BaseEstimator의 상속을 받음
    def fit(self, X, y):
        pass
    def predict(self, X):
        return np.zeros((X.shape[0], 1), dtype=int)

In [3]:
from sklearn.datasets import load_digits

digits = load_digits()
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [4]:
digits.target[0]

0

In [5]:
from sklearn.model_selection import train_test_split
y = (digits.target == 7).astype(int)
X_train, X_test, y_train, y_test = train_test_split(
    digits.data, y, stratify=y, test_size=0.2, random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1437, 64), (360, 64), (1437,), (360,))

- Decision Tree 분류기

In [6]:
from sklearn.tree import DecisionTreeClassifier
dtc =DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train, y_train)
pred = dtc.predict(X_test)

In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9611111111111111

- MyFakeClassfier

In [8]:
my_clf = MyFakeClassfier()
my_clf.fit(X_train, y_train)
my_pred = my_clf.predict(X_test)
accuracy_score(y_test, my_pred)

0.9

### 오차행렬(Confusion Matrix)

In [9]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, my_pred)

array([[324,   0],
       [ 36,   0]], dtype=int64)

In [10]:
confusion_matrix(y_test, pred)

array([[317,   7],
       [  7,  29]], dtype=int64)

### 정밀도와 재현율
- 정확도가 만능이 아니고, 정확도 대신 정밀도와 재현율을 사용할 수 있다 !

In [11]:
from sklearn.metrics import precision_score, recall_score

precision_score(y_test, pred), recall_score(y_test, pred)

(0.8055555555555556, 0.8055555555555556)